import {json,err,clean,publicRest,ensureSeed,first,hashText} from '../_lib.js';

function mapNominatim(r){return r}
function extractGoogle(url){try{const u=new URL(url);let m=u.href.match(/@(-?\d+(?:\.\d+)?),(-?\d+(?:\.\d+)?)/);if(m)return {lat:+m[1],lng:+m[2],name:decodeURIComponent((u.pathname.match(/\/place\/([^/]+)/)||[])[1]||'').replace(/\+/g,' '),url:u.href};const q=u.searchParams.get('q')||u.searchParams.get('query')||'';m=q.match(/(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)/);return {lat:m?+m[1]:null,lng:m?+m[2]:null,name:decodeURIComponent((u.pathname.match(/\/place\/([^/]+)/)||[])[1]||q).replace(/\+/g,' '),url:u.href}}catch{return {}}}
async function resolveMapsLink(q){let final=q;try{const u=new URL(q);if(/(^|\.)goo\.gl$|maps\.app\.goo\.gl$/.test(u.hostname)){const r=await fetch(q,{redirect:'follow',headers:{'user-agent':'PersFavourites/0.27c'}});final=r.url||q;try{r.body?.cancel?.()}catch{}}}catch{}return {...extractGoogle(final),url:final}}
async function nominatimSearch(q){const u=new URL('https://nominatim.openstreetmap.org/search');u.searchParams.set('q',q);u.searchParams.set('format','jsonv2');u.searchParams.set('addressdetails','1');u.searchParams.set('extratags','1');u.searchParams.set('namedetails','1');u.searchParams.set('limit','8');const r=await fetch(u,{headers:{Accept:'application/json','User-Agent':'PersFavourites/0.27c'}});if(!r.ok)throw new Error(`Place search failed (${r.status})`);return await r.json()}
async function nominatimReverse(lat,lng){const u=new URL('https://nominatim.openstreetmap.org/reverse');u.searchParams.set('lat',lat);u.searchParams.set('lon',lng);u.searchParams.set('format','jsonv2');u.searchParams.set('addressdetails','1');u.searchParams.set('extratags','1');u.searchParams.set('namedetails','1');const r=await fetch(u,{headers:{Accept:'application/json','User-Agent':'PersFavourites/0.27c'}});if(!r.ok)throw new Error(`Place lookup failed (${r.status})`);return await r.json()}

const querySchema={type:'object',additionalProperties:false,properties:{mode:{type:'string',enum:['search','aggregate']},filters:{type:'object',additionalProperties:false,properties:{text:{type:'string'},country:{type:'string'},region:{type:'string'},city:{type:'string'},suburb:{type:'string'},placeType:{type:'string'},cuisine:{type:'string'},minRating:{type:'integer',minimum:0,maximum:5},maxDistanceKm:{type:'number',minimum:0,maximum:500},status:{type:'string',enum:['','favourite','want','visited','unvisited','regular','unrated']},meal:{type:'string'},greatFor:{type:'string'},feature:{type:'string'},dietary:{type:'string'},tag:{type:'string'},wouldGoAgain:{type:'string',enum:['','yes','no']}} ,required:['text','country','region','city','suburb','placeType','cuisine','minRating','maxDistanceKm','status','meal','greatFor','feature','dietary','tag','wouldGoAgain']},sort:{type:'string',enum:['nearest','rating','recent','visited','name','price']},groupBy:{type:'string',enum:['','country','region','city','cuisine','placeType','tag']},metric:{type:'string',enum:['count','averageRating','visits']},topN:{type:'integer',minimum:1,maximum:20}},required:['mode','filters','sort','groupBy','metric','topN']};
async function askPers(request,env){await ensureSeed(env);const s=await first(env,'SELECT ask_pers_enabled,ask_pers_daily_limit FROM app_settings WHERE id=1');if(!s?.ask_pers_enabled)return err('Ask Pers is turned off in Settings.',403);if(!env.OPENAI_API_KEY)return err('Ask Pers is enabled but the OpenAI API key has not been configured.',503);const body=await request.json().catch(()=>({})),question=clean(body.question);if(question.length<3)return err('Enter a question for Pers.');const day=new Date().toISOString().slice(0,10),ip=request.headers.get('cf-connecting-ip')||'unknown',key=(await hashText(`${day}:${ip}`)).slice(0,32),lim=Math.max(1,Math.min(500,+s.ask_pers_daily_limit||50));const use=await first(env,'SELECT request_count FROM ai_usage WHERE usage_date=? AND requester_hash=?',[day,key]);if((use?.request_count||0)>=lim)return err('Ask Pers daily usage limit reached. The Owner can change the limit in Settings.',429);
  const payload={model:env.OPENAI_MODEL||'gpt-5.6-luna',input:[{role:'system',content:[{type:'input_text',text:'You translate questions about a private favourite-places database into a safe structured query plan. Never write SQL. Never invent venue names. Use only the schema fields. For “tonight”, prefer placeType Restaurant and meal Dinner but do not claim a place is open unless the user explicitly says opening hours are stored. Interpret “haven’t visited/tried”, “not visited/tried”, or “never visited/tried” as status unvisited; use want only for an explicit Want to Try request. Use empty strings/zero for unspecified filters.'}]},{role:'user',content:[{type:'input_text',text:question}]}],text:{format:{type:'json_schema',name:'pers_query',strict:true,schema:querySchema}}};
  const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)return err(d?.error?.message||'Ask Pers request failed.',502);let out=d.output_text; if(!out){const txt=[];for(const item of d.output||[])for(const c of item.content||[])if(c.type==='output_text'&&c.text)txt.push(c.text);out=txt.join('');}let plan;try{plan=JSON.parse(out)}catch{return err('Ask Pers returned an unreadable query plan.',502)}await env.PERS_DB.prepare('INSERT INTO ai_usage(usage_date,requester_hash,request_count) VALUES(?,?,1) ON CONFLICT(usage_date,requester_hash) DO UPDATE SET request_count=request_count+1').bind(day,key).run();return json({plan,remaining:Math.max(0,lim-(use?.request_count||0)-1)});
}

export async function onRequest(context){const {request,env}=context;try{await ensureSeed(env);const u=new URL(request.url),action=u.searchParams.get('action')||'bootstrap';if(action==='rest'){const table=u.searchParams.get('table')||'';return json(await publicRest(env,{table,filters:u.searchParams.get('filters')||''}));}if(action==='bootstrap'){const [settings,places,photos,lists]=await Promise.all([publicRest(env,{table:'app_settings'}),publicRest(env,{table:'places'}),publicRest(env,{table:'venue_photos'}),publicRest(env,{table:'app_list_options'})]);return json({settings:settings[0]||{},places,photos,listOptions:lists[0]?.options||{}});}if(action==='place-search'){const q=clean(u.searchParams.get('q'));if(q.length<3)return err('Enter a venue name, location, or Google Maps link.');let results=[];if(/^https?:\/\//i.test(q)){const g=await resolveMapsLink(q);if(Number.isFinite(g.lat)&&Number.isFinite(g.lng)){const rev=await nominatimReverse(g.lat,g.lng);results=[rev];if(g.name){const more=await nominatimSearch(`${g.name} ${rev?.address?.city||rev?.address?.town||rev?.address?.country||''}`);results=[...more,rev];}}else if(g.name)results=await nominatimSearch(g.name);results=results.map(x=>({...x,_googleMapsUrl:g.url}));}else results=await nominatimSearch(q);return json({results:results.slice(0,8)});}if(action==='ask-pers'&&request.method==='POST')return askPers(request,env);return err('Unknown public action',404);}catch(e){return err(e.message||'Request failed',e.status||500)}}
