/* Run with jsdom installed in the test environment. No live services are called. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const root=process.env.PERS_TEST_ROOT||process.cwd();
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const dom=new JSDOM(html,{url:'https://example.test/pers-favourites/',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window;
const run=code=>require('node:vm').runInContext(code,dom.getInternalVMContext());
w.structuredClone=structuredClone;w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;
w.URL.createObjectURL=()=> 'blob:https://example.test/qa';w.URL.revokeObjectURL=()=>{};
w.HTMLElement.prototype.scrollIntoView=()=>{};
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
let photoCalls=0,searchCalls=0,failPhoto=false,geoCalls=0;
const googleRow={id:'google-don',name:'Cafeteria Don Pepe',lat:37.88,lng:-4.77,city:'Córdoba',country:'Spain',photoRef:'places/google-don/photos/test',photoAttribution:[{displayName:'Test Photographer',uri:'https://example.test/author'}],photoGoogleMapsUri:'https://example.test/source',photoFlagContentUri:'https://example.test/report'};
w.fetch=async(url,opts)=>{
 if(String(url).includes('/photo')){photoCalls++;return {ok:!failPhoto,json:async()=>failPhoto?{error:'Google Places demo minute limit reached.'}:{photoUri:'https://example.test/photo.jpg'}};}
 if(opts?.method==='POST'){searchCalls++;return {ok:true,json:async()=>({places:[googleRow]})};}
 return {ok:true,json:async()=>({version:'0.27.30'})};
};
Object.defineProperty(w.navigator,'geolocation',{value:{getCurrentPosition:success=>{geoCalls++;success({coords:{latitude:37.88,longitude:-4.77,accuracy:10}});}}});
const tick=()=>new Promise(r=>setTimeout(r,15));
const ev=id=>w.document.getElementById(id).dispatchEvent(new w.Event('change',{bubbles:true}));
const read=run;
const passes=[];function check(label,fn){try{fn();passes.push(label);}catch(e){e.message=label+': '+e.message;throw e;}}
(async()=>{
 for(const file of ['config.js','geo-fallback.js','branding.js','app.js'])run(fs.readFileSync(path.join(root,file),'utf8'));
 w.document.getElementById('startLocalBtn').click();await tick();
 read(`window.PERS_TEST.seedCatalogue([
 {id:'b',name:'Beta',lat:37.90,lng:-4.77,price:'$',persRating:5,createdAt:'2026-03-01',placeType:'Cafe',country:'Spain',stateRegion:'Andalusia',city:'Córdoba'},
 {id:'c',name:'Charlie',lat:37.881,lng:-4.77,price:'$$',persRating:3,createdAt:'2026-01-01',placeType:'Bar',country:'Spain',stateRegion:'Andalusia',city:'Granada'},
 {id:'a',name:'Alpha',lat:null,lng:null,price:'$$$',persRating:4,createdAt:'2026-02-01',placeType:'Cafe',country:'Australia',stateRegion:'Victoria',city:'Melbourne'}
 ]);personal={[personalKey('a')]:{lastVisited:'2026-03-01'},[personalKey('b')]:{lastVisited:'2026-01-01'},[personalKey('c')]:{lastVisited:'2026-02-01'}};
 state.users.push({id:'qa-viewer',role:'viewer'});userRatings=[{placeId:'a',userId:'qa-viewer',rating:5},{placeId:'b',userId:'qa-viewer',rating:3},{placeId:'c',userId:'qa-viewer',rating:4}];`);
 for(const [sort,expected] of Object.entries({name:['a','b','c'],persRating:['b','a','c'],userRating:['a','c','b'],recent:['b','a','c'],visited:['a','c','b'],price:['b','c','a'],nearest:['c','b','a']})){
  w.document.getElementById('sortSelect').value=sort;ev('sortSelect');await tick();
  check('sort '+sort,()=>assert.deepEqual(Array.from(read('filteredPlaces.map(p=>p.id)')),expected));
  check('rendered order '+sort,()=>assert.deepEqual([...w.document.querySelectorAll('#listPanel article')].map(x=>x.dataset.place),expected));
 }
 check('Nearest requests device location',()=>assert.ok(geoCalls>0));
 check('null coordinates excluded',()=>assert.equal(read('distanceFor(places.find(p=>p.id==="a"))'),null));
 read('currentPosition=null;render()');check('missing GPS visible',()=>assert.match(w.document.getElementById('selectionSummary').textContent,/Location needed/));
 read('filters.type="Cafe";render()');check('filter works',()=>assert.equal(read('filteredPlaces.length'),2));
 check('chips outside collapsed filters',()=>assert.equal(w.document.getElementById('catalogueFiltersPanel').contains(w.document.getElementById('activeChips')),false));
 w.document.querySelector('[data-clear-filter="type"]').click();check('remove chip works',()=>assert.equal(read('filters.type'),''));
 read(`Object.assign(places.find(p=>p.id==='b'),{cuisine:'Spanish',mealTypes:['Breakfast'],greatFor:['Coffee'],features:['Outdoor Seating'],dietary:['Vegetarian'],tags:['Old Town'],openNow:true});personal[personalKey('b')].want=true;currentPosition={lat:37.88,lng:-4.77};`);
 for(const [id,value] of Object.entries({typeFilter:'Cafe',cuisineFilter:'Spanish',priceFilter:'$',mealFilter:'Breakfast',greatForFilter:'Coffee',featureFilter:'Outdoor Seating',dietaryFilter:'Vegetarian',tagFilter:'Old Town',statusFilter:'want',ratingFilter:'5',distanceFilter:'5',openNowFilter:'yes'})){
  read('resetFilters()');w.document.getElementById(id).value=value;ev(id);await tick();
  check('filter '+id,()=>assert.ok(read('filteredPlaces.length')<3));
 }
 read('resetFilters();');
 w.document.getElementById('searchInput').value='no matching venue';
 w.document.getElementById('searchInput').dispatchEvent(new w.Event('input',{bubbles:true}));
 w.document.getElementById('editLocationBtn').click();
 check('Country accepts focus with zero search results',()=>assert.equal(w.document.activeElement.id,'countryFilter'));
 check('Country enabled with zero search results',()=>assert.equal(w.document.getElementById('countryFilter').disabled,false));
 for(const [id,value] of [['countryFilter','Spain'],['regionFilter','Andalusia'],['cityFilter','Córdoba']]){
  const el=w.document.getElementById(id);el.focus();
  check(id+' receives focus',()=>assert.equal(w.document.activeElement,el));
  el.value=value;el.dispatchEvent(new w.Event('input',{bubbles:true}));
 }
 check('Location commits with unrelated search active',()=>assert.equal(read('filters.city'),'Córdoba'));
 check('City selection closes location panel',()=>assert.equal(w.document.getElementById('coreLocationFields').classList.contains('hidden'),true));
 w.document.getElementById('editLocationBtn').click();w.document.getElementById('locationDoneBtn').click();
 check('Done closes panel',()=>assert.equal(w.document.getElementById('coreLocationFields').classList.contains('hidden'),true));
 w.document.getElementById('editLocationBtn').click();w.document.getElementById('editLocationBtn').click();
 check('Hide closes panel',()=>assert.equal(w.document.getElementById('coreLocationFields').classList.contains('hidden'),true));
 w.document.getElementById('clearLocationBtn').click();
 check('Clear resets location',()=>assert.equal(read('[filters.country,filters.region,filters.city].join("")'),''));
 check('Clear leaves Country enabled',()=>assert.equal(w.document.getElementById('countryFilter').disabled,false));
 w.document.getElementById('clearSearchBtn').click();read('resetFilters()');

 check('managed cuisine values retained',()=>assert.ok(Array.from(read('masterValues("cuisine")')).includes('Spanish')));
 w.document.getElementById('sourceGoogle').checked=true;ev('sourceGoogle');check('source summary updates',()=>assert.match(w.document.getElementById('selectionSummary').textContent,/Pers \+ Google/));
 read(`externalPlaceResults=[Object.assign(googleWorkerResultToPlace(${JSON.stringify(googleRow)}),{provider:'Google Places'})];render()`);await tick();
 check('external Google photo rendered',()=>assert.ok(w.document.querySelector('#externalGoogleResultsPanel .google-place-photo')));
 check('attribution preserved',()=>assert.match(w.document.querySelector('#externalGoogleResultsPanel .google-photo-attribution').textContent,/Test Photographer.*View source photo.*Report/));
 const externalFrame=w.document.querySelector('#externalGoogleResultsPanel [data-google-photo-place]');
 const before=photoCalls;read('render()');await tick();check('sort/render reuses displayed photo',()=>assert.equal(photoCalls,before));
 check('external sorting retains its photo element',()=>assert.equal(w.document.querySelector('#externalGoogleResultsPanel [data-google-photo-place]'),externalFrame));
 w.document.getElementById('sourceGoogle').checked=false;ev('sourceGoogle');check('source off hides its results',()=>assert.equal(w.document.getElementById('externalGoogleResultsPanel'),null));
 read(`places.push(normalizeLegacyPlace({id:'don',name:'Cafeteria Don Pepe',googlePlaceId:'google-don',city:'Córdoba',lat:37.88,lng:-4.77}));render()`);await tick();
 check('saved Google photo rendered',()=>assert.ok(w.document.querySelector('[data-google-photo-place="don"] .google-place-photo')));
 failPhoto=true;read('displayedGooglePhotos.clear();$("listPanel").replaceChildren();render()');await new Promise(r=>setTimeout(r,1500));
 check('provider failure visible',()=>assert.match(w.document.querySelector('[data-google-photo-place="don"]').textContent,/minute limit reached/));
 failPhoto=false;w.document.querySelector('[data-google-photo-place="don"] button').click();await tick();check('retry photo recovers',()=>assert.ok(w.document.querySelector('[data-google-photo-place="don"] .google-place-photo')));
 const donFrame=w.document.querySelector('[data-google-photo-place="don"]');
 const callsBeforeSort=photoCalls;
 w.document.getElementById('sortSelect').value='name';ev('sortSelect');await tick();
 check('sorting retains the same venue photo element',()=>assert.equal(w.document.querySelector('[data-google-photo-place="don"]'),donFrame));
 check('sorting makes no new saved photo request',()=>assert.equal(photoCalls,callsBeforeSort));
 read(`places.push(normalizeLegacyPlace({id:'casa',name:'Casa El Pimpo',city:'Córdoba',googlePlaceId:'google-casa'}));render()`);await tick();
 check('adding a venue retains existing images',()=>assert.equal(w.document.querySelector('[data-google-photo-place="don"]'),donFrame));
 check('new venue cannot borrow Don Pepe photo',()=>assert.equal(w.document.querySelector('[data-google-photo-place="casa"] .google-place-photo'),null));
 check('provider ID mismatch rejects same name',()=>assert.equal(read(`providerPhotoMatch({googlePlaceId:'other',name:'Cafeteria Don Pepe'},[${JSON.stringify(googleRow)}])`),undefined));
 check('ambiguous name matches rejected',()=>assert.equal(read(`providerPhotoMatch({name:'Cafeteria Don Pepe',city:'Córdoba',country:'Spain'},[${JSON.stringify(googleRow)},${JSON.stringify(googleRow)}])`),null));
 read('filters.type="Cafe";render()');w.document.getElementById('summaryToggle').click();
 check('summary collapses',()=>assert.equal(w.document.getElementById('selectionDetails').hidden,true));
 check('collapsed summary keeps filter count',()=>assert.match(w.document.getElementById('summaryOverview').textContent,/1 filter/));
 check('summary button has a clear Filters label and decorative chevrons',()=>{const b=w.document.getElementById('summaryToggle');assert.equal(b.textContent,'Filters');assert.equal(b.querySelector('svg').getAttribute('aria-hidden'),'true');assert.equal(b.getAttribute('aria-label'),'Filters: expand details');});
 check('separate editing control is distinguishable',()=>assert.match(w.document.getElementById('filtersToggleBtn').textContent,/Edit filters/));
 check('summary exposes expanded state',()=>assert.equal(w.document.getElementById('summaryToggle').getAttribute('aria-expanded'),'false'));
 read('render()');check('collapse survives rendering',()=>assert.equal(w.document.getElementById('selectionDetails').hidden,true));
 check('collapse preference saved',()=>assert.ok(w.localStorage.getItem('pers-v027f-db:pers-favourites-per-trial').includes('"summaryCollapsed":true')));
 w.document.getElementById('summaryToggle').click();check('summary expands without clearing filters',()=>{assert.equal(w.document.getElementById('selectionDetails').hidden,false);assert.equal(read('filters.type'),'Cafe');});
 read('filters=defaultFilters();places=places.filter(p=>p.id!=="casa");');
 read('render()');await tick();
 await read('openPlaceEditor()');w.document.getElementById('placeName').value='QA newly saved venue';
 const retainedBeforeSave=w.document.querySelector('[data-google-photo-place="don"]');
 await read('savePlace({preventDefault(){}})');await tick();
 check('actual Save Place retains existing photo',()=>assert.equal(w.document.querySelector('[data-google-photo-place="don"]'),retainedBeforeSave));
 check('actual Save Place persists new venue',()=>assert.ok(w.localStorage.getItem('pers-v027f-db:pers-favourites-per-trial').includes('QA newly saved venue')));
 read('places=places.filter(p=>p.name!=="QA newly saved venue");');
 const normalFetch=w.fetch,pendingPhotos=new Map();
 w.fetch=async(url,options)=>{
  const ref=options?.body?JSON.parse(options.body).photoRef:'';
  if(String(url).includes('/photo')&&ref?.includes('race-'))return new Promise(resolve=>pendingPhotos.set(ref,()=>resolve({ok:true,json:async()=>({photoUri:'https://example.test/'+ref.split('/')[1]+'.jpg'})})));
  return normalFetch(url,options);
 };
 read(`places.push(...['race-one','race-two'].map(id=>normalizeLegacyPlace({id,name:id,googlePlaceId:id,city:'Córdoba'})));for(const p of places.filter(p=>p.id.startsWith('race-')))liveExternalByPlace.set(p.id,{googlePlaceId:p.googlePlaceId,googlePhotoRef:'places/'+p.id+'/photos/test'});render()`);await tick();
 w.document.getElementById('sortSelect').value='recent';ev('sortSelect');await tick();
 pendingPhotos.get('places/race-two/photos/test')();await tick();pendingPhotos.get('places/race-one/photos/test')();await tick();
 for(const id of ['race-one','race-two'])check('out-of-order photo stays with '+id,()=>assert.equal(w.document.querySelector('[data-google-photo-place="'+id+'"] img.google-place-photo').src,'https://example.test/'+id+'.jpg'));
 w.fetch=normalFetch;read('places=places.filter(p=>!p.id.startsWith("race-"));');
 const originalFetch=w.fetch;let finishOld;
 w.fetch=async(url,options)=>String(url).includes('/photo')?new Promise(resolve=>{finishOld=()=>resolve({ok:true,json:async()=>({photoUri:'https://example.test/old-venue.jpg'})});}):originalFetch(url,options);
 const stalePhoto=read(`window.qaChangingPlace={id:'changed',name:'Old venue',googlePlaceId:'old',googlePhotoRef:'places/old/photos/one'};resolveGooglePhoto(window.qaChangingPlace)`);
 await tick();read(`window.qaChangingPlace.name='New venue';window.qaChangingPlace.googlePlaceId='new';`);finishOld();
 const staleResult=await stalePhoto;check('late response from edited venue rejected',()=>assert.equal(staleResult,null));w.fetch=originalFetch;
 read(`photos=[{id:'shared',placeId:'b',status:'approved'},{id:'shared',placeId:'c',status:'approved'}]`);
 const ambiguousBlob=await read('photoObjectUrl(photos[0])');check('duplicate photo ID across venues fails closed',()=>assert.equal(ambiguousBlob,''));read('photos=[]');
 check('photo names not persisted',()=>assert.ok(!w.localStorage.getItem('pers-v027f-db:pers-favourites-per-trial').includes('places/google-don/photos/test')));
 read('filters.country="Spain";filters.region="Andalusia";filters.city="Córdoba";populateFilterOptions();render()');check('geographic cascade',()=>assert.deepEqual(Array.from(read('filteredPlaces.map(p=>p.id)')),['b']));
 read('filters=defaultFilters();photos=[1,2,3,4,5].map(n=>({id:"ph"+n,placeId:"b",status:"approved",isCover:true,sortOrder:n}));');check('collage capped at four',()=>assert.equal(read('bannerPhotosForPlace("b").length'),4));
 read('currentUser={id:"qa-viewer",role:"viewer"};render()');check('viewer cannot edit',()=>assert.equal(w.document.querySelectorAll('#listPanel [data-edit]').length,0));
 check('owner rating excluded from user average',()=>{read('userRatings.push({placeId:"a",userId:state.users.find(u=>u.role!=="viewer").id,rating:1})');assert.equal(read('userRatingSummary("a").avg'),5);});
 read('archiveMode=false;places[0].archivedAt="2026-09-20";render()');check('archived venue hidden',()=>assert.ok(!read('filteredPlaces.some(p=>p.id==="b")')));
 read('archiveMode=true;render()');check('archive venue retained',()=>assert.ok(read('filteredPlaces.some(p=>p.id==="b")')));
 read(`currentUser=state.users.find(u=>u.role==='owner');state.users.push({id:'rating-qa-1',role:'viewer'},{id:'rating-qa-2',role:'viewer'});userRatings=[{placeId:'b',userId:'rating-qa-1',rating:3},{placeId:'b',userId:'rating-qa-2',rating:4}];places.find(p=>p.id==='b').persRating=4;openDetail('b')`);
 const ratingRows=[...w.document.querySelectorAll('.venue-rating-row')];
 check('Pers and User ratings share the same row structure',()=>assert.deepEqual(ratingRows.map(row=>[...row.children].map(el=>el.className)),[...Array(2)].map(()=>['rating-label','stars','rating-value','rating-caption muted small'])));
 check('both rating rows have five stars',()=>assert.deepEqual(ratingRows.map(row=>row.querySelectorAll('.rating-star').length),[5,5]));
 check('user average displays fractional stars',()=>{assert.equal(ratingRows[1].querySelector('.rating-value').textContent,'3.5 / 5');assert.equal(ratingRows[1].querySelectorAll('.rating-star')[3].style.getPropertyValue('--star-fill'),'50%');});
 check('Owner can edit only Pers rating',()=>{assert.equal(ratingRows[0].querySelectorAll('button[data-pers-rate]').length,5);assert.equal(ratingRows[1].querySelectorAll('button').length,0);});
 read(`currentUser={id:'rating-qa-1',role:'viewer'};openDetail('b')`);
 check('viewer cannot edit Pers average',()=>assert.equal(w.document.querySelectorAll('[data-rating-kind="pers"] button').length,0));
 check('viewer retains separate personal rating controls',()=>assert.equal(w.document.querySelectorAll('[data-user-stars="b"] button').length,5));
 read('photos=[];archiveMode=false;filters=defaultFilters();displayedGooglePhotos.clear();googlePhotoFailures.clear();$("listPanel").replaceChildren();');
 failPhoto=true;read('render()');await tick();await tick();
 check('list failure reproduced before detail recovery',()=>assert.ok(w.document.querySelector('#listPanel [data-google-photo-place="don"] .photo-unavailable')));
 failPhoto=false;read('for(const failure of googlePhotoFailures.values())failure.at-=61000;openDetail("don")');await tick();await tick();
 check('detail success repairs the existing failed list frame',()=>assert.equal(w.document.querySelector('#listPanel [data-google-photo-place="don"] img').src,'https://example.test/photo.jpg'));
 check('detail and list display the same recovered photo',()=>assert.equal(w.document.querySelector('#detailDialog [data-google-photo-place="don"] img').src,w.document.querySelector('#listPanel [data-google-photo-place="don"] img').src));
 check('recovered list retains photo attribution',()=>assert.match(w.document.querySelector('#listPanel [data-google-photo-place="don"]').textContent,/Test Photographer/));
 read('render()');await tick();
 check('no repeated actions on venue rows',()=>assert.equal(w.document.querySelectorAll('#listPanel [data-venue-action]').length,0));
 read('selectVenue("a")');
 check('shared bar exposes ordered actions',()=>assert.deepEqual([...w.document.querySelectorAll('#venueBar [data-venue-action]')].map(x=>x.dataset.venueAction),['open','directions','website','call','book','tripadvisor']));
 check('missing website disabled',()=>assert.equal(w.document.querySelector('#venueBar [data-venue-action="website"]').disabled,true));
 read('Object.assign(places.find(p=>p.id==="a"),{website:"https://example.test/alpha",phone:"+34 123 456"});render();selectVenue("a")');
 check('shared website and phone actions work',()=>{assert.equal(w.document.querySelector('#venueBar [data-venue-action="website"]').href,'https://example.test/alpha');assert.equal(w.document.querySelector('#venueBar [data-venue-action="call"]').href,'tel:+34123456');});
 w.document.getElementById('venueBarToggle').click();read('selectVenue("don")');
 check('bar remains collapsed after venue change',()=>assert.equal(w.document.getElementById('venueBarActions').hidden,true));
 w.document.getElementById('venueBarToggle').click();
 check('expanded bar targets current venue',()=>assert.equal(w.document.querySelector('#venueBar [data-open]').dataset.open,'don'));
 read('setView("map",false);syncVenueBar()');check('map hides bar',()=>assert.equal(w.document.getElementById('venueBar').hidden,true));read('setView("list",false);syncVenueBar()');
 read('filters.country="Spain";filters.region="Andalusia";filters.city="Málaga";populateFilterOptions();render()');
 check('location without venues retained',()=>assert.equal(read('filters.city'),'Málaga'));
 check('empty list hides bar',()=>assert.equal(w.document.getElementById('venueBar').hidden,true));
 read('filters=defaultFilters();currentUser=state.users.find(u=>u.role==="owner");places.find(p=>p.id==="a").stateRegion="Andalicia";places.find(p=>p.id==="a").country="Spain"');
 await read('openPlaceEditor("a")');await tick();
 check('legacy Andalicia canonicalised in editor',()=>assert.equal(w.document.getElementById('placeRegion').value,'Andalusia'));
 const region=w.document.getElementById('placeRegion');region.focus();region.value='Anda';region.dispatchEvent(new w.Event('input',{bubbles:true}));await new Promise(r=>setTimeout(r,260));
 check('editor does not replace partially typed region',()=>assert.equal(region.value,'Anda'));
 region.value='Andalusia';region.dispatchEvent(new w.Event('change',{bubbles:true}));await tick();
 await read('findProviderMatch("google")');
 check('Google match selection lists results',()=>assert.ok(w.document.querySelector('#providerMatches button')));
 w.document.querySelector('#providerMatches button').click();
 check('Google match selection sets ID and link',()=>{assert.equal(w.document.getElementById('placeGoogleId').value,'google-don');assert.match(w.document.getElementById('placeGoogleUrl').value,/google-don/);});
 const originalTA=read('tripadvisorSearch');w.__taMock=async()=>[{name:'Coffee Club',tripadvisorLocationId:'1234',tripadvisorUrl:'https://www.tripadvisor.com/Restaurant_Review-d1234.html'}];read('tripadvisorSearch=window.__taMock');await read('findProviderMatch("tripadvisor")');w.document.querySelector('#providerMatches button').click();
 check('TripAdvisor selection sets ID and link',()=>{assert.equal(w.document.getElementById('placeTripadvisorId').value,'1234');assert.match(w.document.getElementById('placeTripadvisorUrl').value,/1234/);});w.__taOriginal=originalTA;read('tripadvisorSearch=window.__taOriginal');
 w.document.getElementById('placeGoogleId').value='verified-google';w.document.getElementById('placeTripadvisorId').value='123456';
 await read('savePlace({preventDefault(){}})');await read('openPlaceEditor("a")');await tick();
 check('edited region survives save and reopen',()=>assert.equal(region.value,'Andalusia'));
 check('provider IDs survive save and reopen',()=>{assert.equal(w.document.getElementById('placeGoogleId').value,'verified-google');assert.equal(w.document.getElementById('placeTripadvisorId').value,'123456');});
 check('corrected region persists in saved data',()=>assert.equal(read('JSON.parse(localStorage.getItem(LS_DB)).places.find(p=>p.id==="a").stateRegion'),'Andalusia'));
 w.document.getElementById('placeGoogleId').value='';w.document.getElementById('placeTripadvisorId').value='';await read('savePlace({preventDefault(){}})');
 check('clearing provider IDs persists',()=>{assert.equal(read('places.find(p=>p.id==="a").googlePlaceId'),'');assert.equal(read('places.find(p=>p.id==="a").tripadvisorLocationId'),'');});
 read('currentUser={id:"qa-viewer",role:"viewer"}');const beforeSave=read('JSON.stringify(places)');await read('savePlace({preventDefault(){}})');check('viewer save rejected',()=>assert.equal(read('JSON.stringify(places)'),beforeSave));
 for(const dialog of w.document.querySelectorAll('dialog')){
   check(dialog.id+' has one bottom Return control',()=>{assert.equal(dialog.querySelectorAll('.subpage-return button').length,1);assert.equal(dialog.lastElementChild.className,'subpage-return');assert.equal(dialog.lastElementChild.firstElementChild.type,'button');});
   dialog.showModal();dialog.querySelector('.subpage-return button').click();
   check(dialog.id+' Return closes the subpage',()=>assert.equal(dialog.open,false));
 }
 check('pinch zoom remains enabled',()=>assert.doesNotMatch(w.document.querySelector('meta[name="viewport"]').content,/user-scalable\s*=\s*no|maximum-scale/));
 w.scrollTo=()=>{};
 const anchor=w.document.getElementById('catalogueTopAnchor');anchor.getBoundingClientRect=()=>({top:-20});w.dispatchEvent(new w.Event('scroll'));
 check('scroll compacts top controls and exposes return button',()=>{assert.ok(w.document.getElementById('catalogueTopControls').classList.contains('compact'));assert.equal(w.document.getElementById('backToTopBtn').hidden,false);assert.match(w.document.getElementById('filtersToggleBtn').textContent,/Filters/);});
 w.document.getElementById('filtersToggleBtn').click();
 check('compact Filters restores top and opens criteria',()=>{assert.equal(read('catalogueFiltersOpen'),true);assert.equal(w.document.getElementById('catalogueTopControls').classList.contains('compact'),false);});
 w.dispatchEvent(new w.Event('scroll'));w.document.getElementById('backToTopBtn').click();
 check('Top restores full controls without granting Add access',()=>{assert.equal(w.document.getElementById('backToTopBtn').hidden,true);assert.equal(w.document.getElementById('adminActions').classList.contains('hidden'),false);assert.equal(read('canEdit()'),false);});
 read(`archiveMode=false;filters=defaultFilters();photos=[{id:'nav1',placeId:'a',status:'approved',isCover:true},{id:'nav2',placeId:'a',status:'approved',isCover:true}];render()`);
 const thumbnail=w.document.querySelector('[data-venue-photos="a"]');thumbnail.click();
 check('thumbnail opens named photo viewer',()=>{assert.equal(w.document.getElementById('photoViewerDialog').open,true);assert.equal(w.document.getElementById('photoPosition').textContent,'1 / 2');assert.equal(read('activeVenueId'),'a');});
 w.document.getElementById('photoNext').click();
 check('Next advances within the same venue',()=>{assert.equal(w.document.getElementById('photoPosition').textContent,'2 / 2');assert.equal(w.document.getElementById('photoNext').disabled,true);assert.equal(read('viewerPhotos[viewerIndex].placeId'),'a');});
 w.document.getElementById('photoPrevious').click();
 check('Previous returns to first photo',()=>assert.equal(w.document.getElementById('photoPosition').textContent,'1 / 2'));
 w.document.getElementById('photoViewerClose').click();
 check('photo Close returns to list',()=>assert.equal(w.document.getElementById('photoViewerDialog').open,false));
 w.document.querySelector('[data-place="a"] h3').click();
 check('name selects row without opening photos',()=>{assert.equal(read('activeVenueId'),'a');assert.equal(w.document.getElementById('photoViewerDialog').open,false);});
 thumbnail.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));
 check('keyboard thumbnail opens viewer',()=>assert.equal(w.document.getElementById('photoViewerDialog').open,true));
 // v29: partial typing, asynchronous option refresh and clear/reselection.
 for(const dialog of w.document.querySelectorAll('dialog'))dialog.close();
 read(`currentUser=state.users.find(u=>u.role==='owner');archiveMode=false;resetFilters();`);
 const cityInput=w.document.getElementById('cityFilter');
 const input=(id,value)=>{const el=w.document.getElementById(id);el.value=value;el.dispatchEvent(new w.Event('input',{bubbles:true}));};
 input('countryFilter','Spain');input('regionFilter','Andalusia');await tick();
 cityInput.focus();input('cityFilter','Mala');await new Promise(r=>setTimeout(r,280));
 check('v29 partial Málaga input never auto-commits on a timer',()=>{assert.equal(cityInput.value,'Mala');assert.equal(read('filters.city'),'');});
 read('populateFilterOptions()');
 check('v29 background geography refresh preserves city draft',()=>assert.equal(cityInput.value,'Mala'));
 input('cityFilter','Malaga');
 check('v29 unaccented Malaga commits Málaga',()=>assert.equal(read('filters.city'),'Málaga'));
 for(let i=0;i<3;i++){
   read('resetFilters()');input('countryFilter','Spain');input('regionFilter',i===1?'Andulucia':'Andalucía');await tick();input('cityFilter','Malaga');
   check('v29 clear and reselect Málaga '+i,()=>assert.equal(read('filters.city'),'Málaga'));
 }
 cityInput.blur();
 read(`places.push({id:'v29-mal',name:'Málaga test venue',country:'Spain',stateRegion:'Andalucía',city:'Malaga',placeType:'Cafe'});filters.type='Hotel';populateFilterOptions();render();`);
 check('v29 zero results retain Málaga selection and option',()=>{assert.equal(read('filters.city'),'Málaga');assert.ok(read('(searchableChoices.get("cityFilter")||[]).some(x=>geoSame(x.value,"Málaga"))'));});
 read(`filters.type='';render()`);
 check('v29 accented aliases match saved venue',()=>assert.ok(read('filteredPlaces.some(p=>p.id==="v29-mal")')));
 const identityBefore=read('JSON.stringify(currentUser)');read('openAccount();setAccountPane("user",true)');w.document.getElementById('accountClose').click();
 check('v29 settings preserve location and identity',()=>{assert.equal(read('filters.city'),'Málaga');assert.equal(read('JSON.stringify(currentUser)'),identityBefore);});
 w.confirm=()=>true;
 read(`places.push({id:'v29-arch',name:'Disposable archived QA venue',country:'Spain',stateRegion:'Andalusia',city:'Málaga',archivedAt:'2026-09-01'});showArchive()`);
 check('v29 Archive has an explicit exit and authorised Add',()=>{assert.equal(w.document.getElementById('archiveBanner').hidden,false);assert.equal(w.document.getElementById('adminActions').classList.contains('hidden'),false);});
 await read('deleteForever("v29-arch")');read('openAccount();setAccountPane("user",true)');w.document.getElementById('accountClose').click();
 check('v29 delete archive then My Settings returns to Places with same role',()=>{assert.equal(read('archiveMode'),false);assert.equal(read('JSON.stringify(currentUser)'),identityBefore);assert.equal(w.document.getElementById('adminActions').classList.contains('hidden'),false);});
 w.document.getElementById('addPlaceBtn').click();await tick();
 check('v29 Add opens usable editor after navigation sequence',()=>assert.equal(w.document.getElementById('placeDialog').open,true));
 w.document.getElementById('placeName').value='v29 Add after archive';await read('savePlace({preventDefault(){}})');
 check('v29 new venue saves after archive navigation',()=>assert.ok(read('places.some(p=>p.name==="v29 Add after archive"&&!p.archivedAt)')));
 read('showArchive()');w.document.getElementById('returnToPlacesBtn').click();
 check('v29 explicit Back to Places leaves Archive',()=>assert.equal(read('archiveMode'),false));
 read('showArchive()');w.document.getElementById('addPlaceBtn').click();await tick();
 check('v29 Add from Archive returns to active Places',()=>assert.equal(read('archiveMode'),false));read('closePlaceEditor()');
 read(`currentUser={id:'qa-viewer',role:'viewer'};render()`);
 check('v30 viewer sees Add but cannot edit',()=>{assert.equal(w.document.getElementById('adminActions').classList.contains('hidden'),false);assert.equal(read('canEdit()'),false);});
 read('showArchive()');check('v29 viewer cannot enter Archive',()=>assert.equal(read('archiveMode'),false));
 read(`CFG.mode='production';currentUser={id:'qa-sys',role:'sysadmin'};render()`);check('v29 sysadmin without Owner cannot Add',()=>assert.equal(read('canEdit()'),false));
 read(`currentUser={id:'qa-dual',role:'sysadmin',roles:['sysadmin','owner']};render()`);check('v29 dual-role account retains Add',()=>assert.equal(read('canEdit()'),true));

 read(`CFG.mode='local';currentUser=state.users.find(u=>u.role==='owner');resetFilters();`);
 const suggestion=(id,name)=>[...w.document.getElementById(id+'Suggestions').querySelectorAll('button')].find(b=>b.textContent===name);
 input('countryFilter','Spai');
 check('v30 Spai visibly offers Spain without completing text',()=>{assert.equal(w.document.getElementById('countryFilter').value,'Spai');assert.equal(w.document.getElementById('countryFilterSuggestions').hidden,false);assert.ok(suggestion('countryFilter','Spain'));});
 suggestion('countryFilter','Spain').click();await tick();input('regionFilter','Andal');
 check('v30 partial region visibly offers Andalusia',()=>assert.ok(suggestion('regionFilter','Andalusia')));
 suggestion('regionFilter','Andalusia').click();await tick();input('cityFilter','Mala');
 check('v30 Mala visibly offers Málaga',()=>assert.ok(suggestion('cityFilter','Málaga')));
 suggestion('cityFilter','Málaga').click();
 check('v30 tapping suggestion applies complete location',()=>assert.equal(read('filters.city'),'Málaga'));
 read('resetFilters()');input('countryFilter','Spai');w.document.getElementById('countryFilter').dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));
 check('v30 keyboard reaches Spain option',()=>assert.equal(w.document.activeElement.textContent,'Spain'));w.document.activeElement.click();
 check('v30 keyboard choice commits country',()=>assert.equal(read('filters.country'),'Spain'));
 read('currentUser={id:"qa-viewer",role:"viewer"};render()');w.document.getElementById('addPlaceBtn').click();
 check('v30 viewer Add opens identity guidance without granting permission',()=>{assert.equal(w.document.getElementById('accountDialog').open,true);assert.equal(w.document.getElementById('placeDialog').open,false);assert.equal(read('canEdit()'),false);assert.equal(w.document.activeElement.id,'localRoleSelect');});
 w.document.getElementById('accountClose').click();read('currentUser=state.users.find(u=>u.role==="owner");render()');w.document.getElementById('addPlaceBtn').click();await tick();
 w.document.getElementById('placeName').value='v30 new venue via suggestions';input('placeCountry','Spai');check('editor Spain suggestion',()=>assert.ok(suggestion('placeCountry','Spain')));suggestion('placeCountry','Spain').click();await tick();input('placeRegion','Andal');check('editor Andalusia suggestion',()=>assert.ok(suggestion('placeRegion','Andalusia')));suggestion('placeRegion','Andalusia').click();await tick();input('placeCity','Mala');check('editor Málaga suggestion',()=>assert.ok(suggestion('placeCity','Málaga')));suggestion('placeCity','Málaga').click();
 w.document.getElementById('savePlaceBtn').click();await tick();
 check('v30 Add form saves through actual submit button',()=>assert.ok(read('places.some(p=>p.name==="v30 new venue via suggestions"&&p.city==="Málaga"&&p.country==="Spain")')));
 check('v30 saved venue persists in local storage',()=>assert.ok(read('JSON.parse(localStorage.getItem(LS_DB)).places.some(p=>p.name==="v30 new venue via suggestions")')));
 console.log(JSON.stringify({passed:passes.length,passes,photoCalls,searchCalls},null,2));dom.window.close();
})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1;});
